<template>
  <div class="domains">
    <b-container>
      <b-row>
        <b-col>
          <h1>Search a specific domain</h1>
          <p>
            In this service you will be able to find information about any domain you want. Keep in mind that some errors can be generated by the way you write down the url.
          </p>
        </b-col>
      </b-row>
    </b-container>
    
    <b-container class="bv-row">
      <b-row>
        <b-col>
          <b-card tag="article" class="mb-2">
            <img alt="browser logo" style="width:60px" class="card-img-top" src="../assets/language-24px.svg">
            <b-card-body>
              <b-card-title>
                Find a domain
              </b-card-title>
              <b-card-text>
                This will give you some information.
              </b-card-text>

              <b-form inline @submit="onSubmit" @reset="onReset" v-if="show">
                <label class="sr-only" for="inline-form-input-domain">Domain</label>
                <b-input
                  id="inline-form-input-domain"
                  class="mb-2 mr-sm-2 mb-sm-0"
                  placeholder="google.com"
                  v-model="form.domain"
                  required
                ></b-input>

                <b-button type="submit" style="margin-right: 5px" variant="primary">Go!</b-button>
                <b-button type="reset" variant="danger">Reset</b-button>
              </b-form>
              <b-card class="mt-3" header="Form Data Result">
                <pre class="m-0">{{ form }}</pre>
              </b-card>


              <ul class="list-group row" v-if="domains && domains.length">
                <li class="list-group-item col-xs-6 col-sm-4 col-md-3" v-for="domain of domains" v-bind:key="domain.id">
                  <p>{{domain.domain}}</p>
                </li>
              </ul>

              <ul class="list-group row" v-if="errors_d && errors_d.length">
                <li class="list-group-item col-xs-6 col-sm-4 col-md-3" v-for="error_d of errors_d" v-bind:key="error_d.id">
                  <p>{{error.message}}</p>
                </li>
              </ul>
              <br>
            </b-card-body>
          </b-card>
        </b-col>
      </b-row>
    </b-container>
  </div>
</template>

<script>
import axios from 'axios';

export default {
  data() {
    return {
      domains: [],
      errors_d: [],
      form: {
        domain: ''
      },
      show: true
    }
  },

  methods: {
    onSubmit(evt) {
      evt.preventDefault()
      alert(JSON.stringify(this.form))
      console.log('HERE')
      var base_url = "http://localhost:3000/domain?name="
      var domain = this.form.domain
      var url = base_url.concat(domain)
      axios.get(url)
      .then(response => {
        this.domain = response.data
        console.log(this.domain)
      })
      .catch(e_d => {
        this.errors_d.push(e_d)
      })
    },
    onReset(evt) {
      evt.preventDefault()
      this.form.domain = ''
      this.show = false
      this.$nextTick(() => {
        this.show = true
      })
    }
  },

  // Fetches posts when the component is created.
  created() {

    

    // async / await version (created() becomes async created())
    //
    // try {
    //   const response = await axios.get(`http://jsonplaceholder.typicode.com/posts`)
    //   this.posts = response.data
    // } catch (e) {
    //   this.errors.push(e)
    // }
  }
}
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>
h1 {
  padding: 10px;
  margin-top: 20px;
}
h3 {
  margin: 40px 0 0;
}
ul {
  list-style-type: none;
  padding: 0;
}
li {
  display: inline-block;
  margin: 0 10px;
}
.card {
  margin: 0 auto;
}
.list-group {
  flex-direction: row;
  justify-content: center;
}
.list-group-item {
  border-top-width: 1px !important;
  margin-bottom: 2px;
}
.form-inline {
  display: block;
}
</style>
