<template>
  <div class="domains">
    <b-container>
      <b-row>
        <b-col>
          <h1>Search a specific domain</h1>
          <p>
            In this service you will be able to find information about any domain you want. Keep in mind that some errors can be generated by the way you write down the url.
          </p>
        </b-col>
      </b-row>
    </b-container>
    
    <b-container class="bv-row">
      <b-row>
        <b-col>
          <b-card tag="article" class="mb-2">
            <img alt="browser logo" style="width:60px" class="card-img-top" src="../assets/language-24px.svg">
            <b-card-body>
              <b-card-title>
                Find a domain
              </b-card-title>
              <b-card-text>
                This will give you some information.
              </b-card-text>

              <b-form inline @submit="onSubmit" @reset="onReset" v-if="show">
                <label class="sr-only" for="inline-form-input-domain">Domain</label>
                <b-input
                  id="inline-form-input-domain"
                  class="mb-2 mr-sm-2 mb-sm-0"
                  placeholder="google.com"
                  v-model="form.domain"
                  required
                ></b-input>

                <b-button type="submit" style="margin-right: 5px" variant="primary">Go!</b-button>
                <b-button type="reset" variant="danger">Reset</b-button>
              </b-form>

              <div v-if="errors && errors.length > 0">
                <br>
                <ul class="list-group row" v-if="errors && errors.length">
                  <li class="list-group-item col-xs-6 col-sm-4 col-md-3" v-for="error of errors" v-bind:key="error.id">
                    <p>{{error.response.data}}</p>
                  </li>
                </ul>
                <br>
              </div>

              <div id="SimpleTable" v-if="show_result">
                <b-card class="mt-3" header="Server results">
                  <div v-if="servers && servers.length > 0">
                    <b-table responsive striped hover :items="servers"></b-table>  
                  </div>
                </b-card>

                <b-card class="mt-3" header="Additional information">
                  <b-table-simple hover responsive>
                    <b-tbody>
                      <b-tr>
                        <b-th class="text-center">Servers changed</b-th>
                        <b-td>{{servers_changed}}</b-td>
                      </b-tr>
                      <b-tr>
                        <b-th class="text-center">SSL grade</b-th>
                        <b-td>{{ssl_grade}}</b-td>
                      </b-tr>
                      <b-tr>
                        <b-th class="text-center">Previous SSL grade</b-th>
                        <b-td>{{previous_ssl_grade}}</b-td>
                      </b-tr>
                      <b-tr>
                        <b-th class="text-center">Logo</b-th>
                        <b-td>
                          <img id="DomainLogo" style="width:60px" class="card-img-top" :src="logo">
                        </b-td>
                      </b-tr>
                      <b-tr>
                        <b-th class="text-center">Title</b-th>
                        <b-td>{{title}}</b-td>
                      </b-tr>
                      <b-tr>
                        <b-th class="text-center">Is down</b-th>
                        <b-td>{{is_down}}</b-td>
                      </b-tr>
                    </b-tbody>
                  </b-table-simple>
                </b-card>
              </div>
            </b-card-body>
          </b-card>
        </b-col>
      </b-row>
    </b-container>
  </div>
</template>

<script>
import axios from 'axios';

export default {
  data() {
    return {
      errors: [],
      form: {
        domain: ''
      },
      show: true,
      show_result: false,
      servers: [],
      servers_changed: '',
      ssl_grade: '',
      previous_ssl_grade: '',
      logo: '',
      title: '',
      is_down: ''
    }
  },

  methods: {
    onSubmit(evt) {
      evt.preventDefault()
      alert(JSON.stringify(this.form))
      this.errors = []
      this.servers = []
      this.servers_changed = ''
      this.ssl_grade = ''
      this.previous_ssl_grade = ''
      this.logo = ''
      this.title = ''
      this.is_down = ''
      this.show_result = false
      var base_url = "http://localhost:3000/domain?name="
      var domain = this.form.domain
      var url = base_url.concat(domain)
      axios.get(url)
      .then(response => {
        this.servers = response.data.servers
        this.servers_changed = response.data.servers_changed
        this.ssl_grade = response.data.ssl_grade
        this.previous_ssl_grade = response.data.previous_ssl_grade
        this.logo = response.data.logo
        this.title = response.data.title
        this.is_down = response.data.is_down
        this.show_result = true
      })
      .catch(e => {
        this.errors.push(e)
      })
    },
    onReset(evt) {
      evt.preventDefault()
      this.form.domain = ''
      this.errors = []
      this.servers = []
      this.servers_changed = ''
      this.ssl_grade = ''
      this.previous_ssl_grade = ''
      this.logo = ''
      this.title = ''
      this.is_down = ''
      this.show = false
      this.show_result = false
      this.$nextTick(() => {
        this.show = true
      })
    }
  },

  // Fetches posts when the component is created.
  created() {

    

    // async / await version (created() becomes async created())
    //
    // try {
    //   const response = await axios.get(`http://jsonplaceholder.typicode.com/posts`)
    //   this.posts = response.data
    // } catch (e) {
    //   this.errors.push(e)
    // }
  }
}
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>
h1 {
  padding: 10px;
  margin-top: 20px;
}
h3 {
  margin: 40px 0 0;
}
ul {
  list-style-type: none;
  padding: 0;
}
li {
  display: inline-block;
  margin: 0 10px;
}
.card {
  margin: 0 auto;
}
.list-group {
  flex-direction: row;
  justify-content: center;
}
.list-group-item {
  border-top-width: 1px !important;
  margin-bottom: 2px;
}
.form-inline {
  display: block;
}
</style>
